services:
  - type: web
    name: xem-phim-luan-2026
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
